
var preflight = preflightChecks();
if (preflight) {
  writeResultFile(RESULT_PATH, preflight);
} else {
  try {
    var doc = app.activeDocument;
    var isCMYKDoc = (doc.documentColorSpace === DocumentColorSpace.CMYK);

    // Layers to skip (generated by place_style_guide / place_color_chips)
    var skipLayers = { "Style Guide": true, "Color Chips": true };

    // Collect colors
    var fillColors = [];
    var strokeColors = [];
    for (var i = 0; i < doc.pathItems.length; i++) {
      var item = doc.pathItems[i];
      try {
        if (skipLayers[item.layer.name]) continue;
        if (item.filled) fillColors.push(colorToObject(item.fillColor));
        if (item.stroked) strokeColors.push(colorToObject(item.strokeColor));
      } catch(e) {}
    }

    // Collect fonts and sizes from text frames
    var fontEntries = [];
    var textBounds = [];
    for (var ti = 0; ti < doc.textFrames.length; ti++) {
      var tf = doc.textFrames[ti];
      try {
        if (skipLayers[tf.layer.name]) continue;
        var b = tf.geometricBounds;
        textBounds.push({ left: b[0], top: b[1], right: b[2], bottom: b[3] });
        for (var ri = 0; ri < tf.textRanges.length; ri++) {
          var tr = tf.textRanges[ri];
          try {
            var ca = tr.characterAttributes;
            var fontName = "";
            var fontStyle = "";
            try { fontName = ca.textFont.name; } catch(e2) {}
            try { fontStyle = ca.textFont.style; } catch(e2) {}
            fontEntries.push({
              fontFamily: fontName,
              fontStyle: fontStyle,
              fontSize: ca.size
            });
          } catch(e2) {}
        }
      } catch(e) {}
    }

    // Collect object bounds for spacing analysis
    var objectBounds = [];
    for (var oi = 0; oi < doc.pageItems.length; oi++) {
      try {
        var pItem = doc.pageItems[oi];
        if (skipLayers[pItem.layer.name]) continue;
        var ob = pItem.geometricBounds;
        objectBounds.push({ left: ob[0], top: ob[1], right: ob[2], bottom: ob[3] });
      } catch(e) {}
    }

    writeResultFile(RESULT_PATH, {
      documentColorSpace: isCMYKDoc ? "CMYK" : "RGB",
      fillColors: fillColors,
      strokeColors: strokeColors,
      fontEntries: fontEntries,
      objectBounds: objectBounds
    });
  } catch (e) {
    writeResultFile(RESULT_PATH, { error: true, message: e.message, line: e.line });
  }
}
